### PR TITLE
feat: export sdk

### LINKED ISSUE #437: Library to convert state to SDK format

### PR DESCRIPTION
**Pull request by cazala**
Closes #437

export-sdk

**IMPORTANT**:  make sure you have the latest version of the CLI to test this:

```
npm i -g decentraland@latest
```

~**BLOCKED**: The CLI preview doesn't count the amount of textures the same way as we do on the builder editor, so many scenes that are within the limits on the builder throw once exported:~

Screen Shot 2019-05-06 at 4 25 02 PM

This is fixed now ✅ 

Screen Shot 2019-05-15 at 1 21 11 PM
Screen Shot 2019-05-15 at 1 24 41 PM

~**BLOCKED 2**: The `dcl-scene-writter` doesn't support `NFTShape` components~

This is fixed now ✅ 

Screen Shot 2019-05-15 at 1 16 06 PM

### CODE REVIEW

**Comment by cazala** [comment]
@twaldorf we need an updated copy and we are good to go (:

**Comment by belohlavek** [comment]
Screen Shot 2019-05-02 at 10 07 10
shouldn't this copy mention sdk usage?

**Comment by eordano** [comment]
Unblocked -- CLI release incoming in the next few hours

**Comment by cazala** [comment]
Unblocked by texture count ✅ 

Now blocked by `NFTShape` support on the `dcl-scene-writer` 🚫 

I'll take care of that

**Comment by abarmat** [comment]
Thank you juanca

**Comment by cazala** [comment]
I added support for the NFTShape on the export here (8c497d5a0ef3a6364830c530a54fb0342d184b1e) and left a PR on https://github.com/decentraland/dcl-scene-writer/pull/7 to add support on the scene writer, but that one is blocked as well until we have a version of the SDK that removes the `internal` from `NFTShape` so we can access it.

cc @menduz

**Comment by cazala** [comment]
Ready for review @belohlavek ^.^

**Pull request merged**
