### PR TITLE
feat: add intercom

### LINKED ISSUE #74: Add intercom
Already available on decentraland-dapps

### PR DESCRIPTION
**Pull request by nicosantangelo**
Depends on https://github.com/decentraland/decentraland-dapps/pull/34

~use `npm install --save decentraland-dapps@3.13.0-rc6` to test~

Closes #74

### CODE REVIEW

**Comment by belohlavek** [comment]
@nicosantangelo please update the package-lock and re-run the build :D

**Comment by nicosantangelo** [comment]
> Danis do not eat normal food, please donate a GIF to feed your local Dani

proxy duckduckgo

**Comment by belohlavek** [comment]
Awaiting mat feedback, DO NOT MERGE

**Comment by belohlavek** [comment]
We can show intercom always on the bottom right corner, and we should create an issue to investigate puting the button in the toolbar and styling it accordingly

**Comment by nicosantangelo** [comment]
@belohlavek like this?:

intercom

**Comment by nicosantangelo** [comment]
@belohlavek Updated!

**Pull request merged**
