### PR TITLE
feat: Hide body shape option from editor

### PR DESCRIPTION
**Pull request by fzavalia**
Prevent the user from selecting body shape as a hideable part

### CODE REVIEW

**Review by cazala — CHANGES_REQUESTED** [review]
mm i think this should be done here, where we already hide the head category: https://github.com/decentraland/builder/blob/master/src/modules/item/utils.ts#L337-L343

**Comment by fzavalia** [comment]
> mm i think this should be done here, where we already hide the head category: https://github.com/decentraland/builder/blob/master/src/modules/item/utils.ts#L337-L343

You are right!

**Review by LautaroPetaccio — APPROVED** [review]

**Review by LautaroPetaccio — CHANGES_REQUESTED** [review]
Dismissed my review due to the PR already having a review.

**Comment by fzavalia** [comment]
> Dismissed my review due to the PR already having a review.

Reviewedn't

**Comment by fzavalia** [comment]
> mm i think this should be done here, where we already hide the head category: https://github.com/decentraland/builder/blob/master/src/modules/item/utils.ts#L337-L343

The thing is that getWearableCategories is not used to get what can be overriden and what not.

**Review by cazala — APPROVED** [review]

**Pull request merged**
