### PR TITLE
feat: add a always open popup for shortcut help

### LINKED ISSUE #228: Shortcuts button indicator
screen shot 2019-02-22 at 15 09 14

### PR DESCRIPTION
**Pull request by nicosantangelo**
`npm i`

image
image

Closes #228

### CODE REVIEW

**Comment by cazala** [comment]
I don't think these are blockers but I found two issues:

1. The popup doesn't follow the button when the sidebar is toggled

2. Hovering the button hides popup even without clicking

tultip

**Comment by nicosantangelo** [comment]
> The popup doesn't follow the button when the sidebar is toggled

On it

> Hovering the button hides popup even without clicking

I did this on purpose˜, you think it's better to keep it visible until the user clicks the `x` ?
I supposed you read it already if you hover it

**Comment by nicosantangelo** [comment]
@cazala I added quite a bit of code, sorry. I decided to handle all possible states, like resizes, sidebar, etc, but to do it I had to workaround the abhorrent Popup Component.

**Comment by belohlavek** [comment]
kapture 2019-03-07 at 10 38 16

**Comment by nicosantangelo** [comment]
@belohlavek Updated!

**Pull request merged**
