### PR TITLE
feat: new contest modal styles and text

### LINKED ISSUE #294: Update contest modal styles
screen shot 2019-03-07 at 11 16 04

### PR DESCRIPTION
**Pull request by nicosantangelo**
**From**

screenshot 2019-03-08 at 13 55 05

**To**

screenshot 2019-03-08 at 14 03 09

Closes #294

### CODE REVIEW

**Comment by belohlavek** [comment]
como shipea este pive

**Comment by belohlavek** [comment]
We could delete `market-tiles.png` right?

**Comment by nicosantangelo** [comment]
Oh yes, I thought it was being used for the button and contest badge. Just checked and it's a different image

**Comment by nicosantangelo** [comment]
Updated!

**Pull request merged**
