### PR TITLE
feat: tutorial modal

### LINKED ISSUE #234: Implement tutorial walkthrough

### PR DESCRIPTION
**Pull request by belohlavek**
kapture 2019-03-01 at 12 43 05

Closes #234

### CODE REVIEW

**Comment by cazala** [comment]
My 2 cents: I would go start with drag and drop from the sidebar, then placing items and camera controls. It is the order in which the user will actually do that stuff.

**Comment by cazala** [comment]
ie:

1. Search, drag and drop:

step-1

2. Placing stuff

step-2

3. Arrows/orbits (there's no "gizmo" word on the UI)

step-3

4. Camera

step-4

**Comment by belohlavek** [comment]
I think there's a discussion about including limits as the 4th one and gizmos being mentioned in the first one.

**Comment by twaldorf** [comment]
That order makes more sense for a mini-tutorial, I like mentioning the orbits instead of using the `gizmo` word.

As the interface gets easier to use, we might in the future rely on this more to help people get through whatever funnel we're optimizing, which could mean having the above collapsed into a single interface/workflow slide and an export/deployment slide or something. Just thoughts.

**Comment by twaldorf** [comment]
I'll revise that copy and run it through Eric. I think we should keep the copy up on the top of the slides and not try to overlay it on the gifs.

**Comment by belohlavek** [comment]
Mat's feedback is that we should make only 1 line per slide and keep them overlayed as we have it now

**Comment by twaldorf** [comment]
Ace, him and I are working through it.

**Comment by twaldorf** [comment]
gifs!
tutorial-add
tutorial-camera-optimized
tutorial-movement
tutorial-orbitsarrows

**Pull request merged**
