### PR TITLE
feat: add play-mode to Emotes metadata

### PR DESCRIPTION
**Pull request by juanmahidalgo**

### CODE REVIEW

**Review by cyaiox — APPROVED** [review]

**Review by fzavalia — APPROVED** [review]

**Comment by fzavalia** [comment]
Assuming this urn format is correct `${version}:${type}:${name}:${description}:${category}:${bodyShapeTypes}:${playMode}`

**Comment by juanmahidalgo** [comment]
> Approved assuming this urn format is correct `${version}:${type}:${name}:${description}:${category}:${bodyShapeTypes}:${playMode}`

I believe it doesn't translate into an urn directly. It's parsed later on by the collections graph to create the entities. The urn does not support `playMode` at the end, do you believe that's an issue @fzavalia ?

**Comment by fzavalia** [comment]
> > Approved assuming this urn format is correct `${version}:${type}:${name}:${description}:${category}:${bodyShapeTypes}:${playMode}`
> 
> I believe it doesn't translate into an urn directly. It's parsed later on by the collections graph to create the entities. The urn does not support `playMode` at the end, do you believe that's an issue @fzavalia ?

Seems ok 😄

**Comment by cazala** [comment]
as discussed offline, i'd suggest not incorporating the concept of `playMode` into the system other than for the UI/UX, and keep the value as `loop: boolean` to match the ADR74 schema. So we could just store `0` or `1` in this slot in order to tell the subgraph the boolean value.

**Review by cazala — APPROVED** [review]

**Pull request merged**
