### PR TITLE
feat: free movement

### LINKED ISSUE #224: Free movement mode
oh boy

### PR DESCRIPTION
**Pull request by cazala**
free-movement

Closes #224

### CODE REVIEW

**Comment by belohlavek** [comment]
Please make sure to keep objects inside the parcel bounds when they are dropped on the horizon

**Comment by nicosantangelo** [comment]
I'm not being able to run it. I get a `TypeError: Cannot read property 'NONE' of undefined` (I tried `npm install`ing)

**Comment by cazala** [comment]
@nicosantangelo fixed!

**Comment by belohlavek** [comment]
Removing while moving breaks stuff

**Comment by belohlavek** [comment]
Add Toggle to move/rotate labels

**Pull request merged**
